# Generated by Django 5.0.2 on 2024-02-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner_url',
            field=models.ImageField(blank=True, null=True, upload_to='blog/banner/'),
        ),
    ]
