# Generated by Django 5.0.2 on 2024-02-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_banner_url'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='Blog_blog_author__b24a82_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='Blog_blog_categor_a67a8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='blog',
            name='Blog_blog_title_8cf133_idx',
        ),
    ]
