# Generated by Django 5.0.2 on 2024-02-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_blog_blog_blog_author__b24a82_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='blog/banner/'),
        ),
    ]
